services:
  prospace-test-task:
    image: prospace-test-task
    build:
      context: .
      dockerfile: ProSpaceTestTask/Dockerfile
    
    environment:
      ASPNETCORE_URLS: "http://+:80"
      ConnectionStrings__DefaultConnection: 'Host=postgres;Port=5432;Username=postgres;Password=123;Database=ProSpaceDatabase'
    
    ports:
      - "7070:80"
        
  postgres:
    container_name: postgres-prospase
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: ProSpaceDatabase
    volumes:
      - ./docker_data/prospase_pg_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    ports:
      - "6543:5432"